-- MySQL Script generated by MySQL Workbench
-- 03/25/17 11:54:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mm_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mm_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mm_bd` DEFAULT CHARACTER SET latin1 ;
USE `mm_bd` ;

-- -----------------------------------------------------
-- Table `mm_bd`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`pessoa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(2) NOT NULL COMMENT 'AT=ATIVO\nIN=INATIVO\n',
  `tipo` VARCHAR(1) NOT NULL COMMENT 'F=FISICA\nJ=JURIDICA\n',
  `rua` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(5) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(30) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `dt_atualizacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `dt_cadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`funcionario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('R', 'M', 'N') NOT NULL DEFAULT 'N',
  `pessoa_id` INT(11) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_funcionario_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_funcionario_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mm_bd`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`modulo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NOT NULL COMMENT 'label',
  `pai` INT(11) NULL DEFAULT NULL,
  `statusID` TINYTEXT NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modulo_modulo1_idx` (`pai` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`acesso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `modulo_id` INT(11) NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  `nivel_acesso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acesso_funcionario1_idx` (`funcionario_id` ASC),
  INDEX `fk_acesso_modulo1` (`modulo_id` ASC),
  CONSTRAINT `fk_acesso_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mm_bd`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acesso_modulo1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `mm_bd`.`modulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL COMMENT 'label',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`comanda_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`comanda_mesa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `active` ENUM('y', 'n') NOT NULL DEFAULT 'y',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`unidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL COMMENT 'label',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`produto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `codbar` VARCHAR(255) NULL DEFAULT NULL,
  `categoria_id` INT(11) NOT NULL,
  `nome` VARCHAR(200) NOT NULL COMMENT 'label',
  `descricao` VARCHAR(1000) NULL DEFAULT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `unidade_id` INT(11) NOT NULL,
  `estoque_min` INT(11) NULL DEFAULT '0',
  `estoque` INT(11) NULL DEFAULT '0',
  `tem_estoque` ENUM('y', 'n') NOT NULL DEFAULT 'y',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  UNIQUE INDEX `codbar_UNIQUE` (`codbar` ASC),
  INDEX `fk_produto_categoria1_idx` (`categoria_id` ASC),
  INDEX `fk_produto_unidade1_idx` (`unidade_id` ASC),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mm_bd`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_unidade1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `mm_bd`.`unidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`entrada_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`entrada_produto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('E', 'S') NOT NULL DEFAULT 'E' COMMENT 'E=Entrada, S=Saida',
  `produto_id` INT(11) NOT NULL,
  `fornecedor_id` INT(11) NULL DEFAULT NULL,
  `quantidade` DECIMAL(10,0) NOT NULL,
  `lote` VARCHAR(45) NULL DEFAULT NULL,
  `dt_compra` DATE NULL DEFAULT NULL,
  `dt_validade` DATE NULL DEFAULT NULL,
  `valor_unitario` DECIMAL(7,2) NULL DEFAULT NULL,
  `valor_total` DECIMAL(7,2) NULL DEFAULT NULL,
  `motivo_saida` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entrada_produto_produto1_idx` (`produto_id` ASC),
  INDEX `fk_entrada_produto_pessoa1_idx` (`fornecedor_id` ASC),
  CONSTRAINT `fk_entrada_produto_pessoa1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `mm_bd`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_produto_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `mm_bd`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`fisica` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT(11) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(200) NOT NULL COMMENT 'label',
  `rg` VARCHAR(20) NULL DEFAULT NULL,
  `dt_nascimento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(1) NULL DEFAULT NULL COMMENT 'SEXO:\nH=HOMEM\nM=MULHER\n',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `pessoa_id_UNIQUE` (`pessoa_id` ASC),
  INDEX `fk_fisica_pessoa2_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_fisica_pessoa2`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mm_bd`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`forma_pagto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`forma_pagto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `active` ENUM('y', 'n') NOT NULL DEFAULT 'y',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` INT(11) NULL DEFAULT NULL,
  `desconto` VARCHAR(45) NULL DEFAULT '0',
  `total` DECIMAL(7,2) NULL DEFAULT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('A','F','C') NULL DEFAULT NULL COMMENT 'A = Aberta F = Fechada C = Cancelada',
  `comanda_mesa_id` INT(11) NULL DEFAULT '1',
  `caixa_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `data`),
  INDEX `fk_venda_pessoa1_idx` (`cliente_id`),
  INDEX `FK_venda_comanda_mesa` (`comanda_mesa_id`),
  INDEX `FK_venda_caixa` (`caixa_id`),
  CONSTRAINT `FK_venda_caixa` FOREIGN KEY (`caixa_id`) REFERENCES `caixa` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `FK_venda_comanda_mesa` FOREIGN KEY (`comanda_mesa_id`) REFERENCES `comanda_mesa` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `fk_venda_pessoa1` FOREIGN KEY (`cliente_id`) REFERENCES `pessoa` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=72;



-- -----------------------------------------------------
-- Table `mm_bd`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`itens_venda` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `venda_id` INT(11) NOT NULL,
  `produto_id` INT(11) NOT NULL,
  `quantidade` VARCHAR(45) NULL DEFAULT NULL,
  `valor_unitario` DECIMAL(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itens_venda_venda1_idx` (`venda_id` ASC),
  INDEX `fk_itens_venda_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_itens_venda_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `mm_bd`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `mm_bd`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mm_bd`.`juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mm_bd`.`juridica` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT(11) NOT NULL,
  `cnpj` VARCHAR(100) NOT NULL,
  `razao_social` VARCHAR(200) NOT NULL,
  `nome_fantasia` VARCHAR(200) NOT NULL COMMENT 'label',
  `inscricao_estadual` VARCHAR(100) NULL DEFAULT NULL,
  `ccm` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  UNIQUE INDEX `pessoa_id_UNIQUE` (`pessoa_id` ASC),
  INDEX `fk_juridica_pessoa2_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_juridica_pessoa2`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mm_bd`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF   NOT EXISTS `log` (
 `id`   INT(11)  NOT NULL AUTO_INCREMENT,
 `user` INT(11)  NOT NULL,
 `log`  LONGTEXT NOT NULL,
 `data` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 `ip`   VARCHAR (100) NOT NULL,   
PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `caixa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `valor_inicial` DOUBLE(7,2) NULL DEFAULT '0.00',
  `valor_fechamento` DOUBLE(7,2) NULL DEFAULT '0.00',
  `funcionario_id` INT(11) NOT NULL DEFAULT '0',
  `dt_abertura` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_fechamento` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_caixa_funcionario` (`funcionario_id`),
  CONSTRAINT `FK_caixa_funcionario` FOREIGN KEY (`funcionario_id`) REFERENCES `funcionario` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=14;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
